### PR TITLE
Adding FMOD sound support

### PR DESCRIPTION
**Pull request by MrEveryDay98**
Resubmitting this since I think I finally understand how Git works lol

~~Anyway, currently this does not produce sound (that's why this is a draft), but it compiles without errors as long as the dependency requirements are met. I'm not much of a programmer so I would appreciate any help with this.~~

Sound now functions as intended.
For now, sound files beginning with `music_` will play on loop in their own sound channel. All other sound files play in another channel

**Building with VS:** 
1. Download fmod 2.02.11 from https://www.fmod.com/download (no direct link available)
2. Add <fmod-path>\api\core\inc to VS additional inclusions
3. Add <fmod-path>\api\core\lib\x64 to additional libraries
4. Add fmod_vc.lib to additional dependencies
5. replace SND_LIB_WINDSOUND in preprocessor definitions with SND_LIB_FMOD
6. change `assign_soundlib(soundlib_windsound);` to `assign_soundlib(soundlib_fmod);`

### CODE REVIEW

**Comment by MrEveryDay98** [comment]
I don't know what kind of formatting or placement is wanted for adding to `\sys\windows\Install.windows` so I'll leave that up to the devs

**Comment by MrEveryDay98** [comment]
And as a quick question. Does the game print the message `welcome to NetHack/welcome back to NetHack` before the soundlib is initialized? I think this should be changed, as that message is a great place to start a song file.

**Comment by nhmall** [comment]
I have a few questions embedded below that I hope you can answer without me having to register with fmod.com to obtain the fmod download.

> * Add \api\core\inc to VS additional inclusions
> * Add \api\core\lib\x64 to additional libraries

Those paths, as shown, are in absolute path format. Is the downloader free to place the api directory anywhere on their machine (such as a subdirectory of lib) in the NetHack tree?  
For purposes of discussion, I will assume that those two paths above can safely equate to the following directories relative to the _src_ directory where the command line build is taking place. 
```
    ..\lib\api\core\inc
    ..\lib\api\core\lib\x64
```
Also, for purposes of discussion, let's focus on a _visual studio command line build with nmake_ to work through the details of the integration required.  mingw32 and the visual studio project files are easily modified once you can confirm a working process and working file locations.

This is the typical start to the command line nmake build:
```
cd sys\windows
nhsetup.bat
cd ..\..\src
nmake install
```

> * Add fmod_vc.lib to additional dependencies
> * replace SND_LIB_WINDSOUND in preprocessor definitions with SND_LIB_FMOD

With the new SND_LIB_ support, which your  latest _fmod.c_ attempts to conform to, the builder of NetHack shouldn't have to replace one with the other. Than can both defined (or either, or none).
```
    -DSND_LIB_WINDSOUND -DSND_LIB_FMOD
```
> * change `assign_soundlib(soundlib_windsound);` to `assign_soundlib(soundlib_fmod);`

If you mean in sys\windows\windmain.c, I would suggest doing something like this:
```
#if defined(SND_LIB_FMOD)
    assign_soundlib(soundlib_fmod);
#elif defined(SND_LIB_WINDSOUND)
    assign_soundlib(soundlib_windsound);
#endif
```
That would assign whichever one is defined, and that ordering gives priority to using soundlib_fmod if both are defined. Once set, you wouldn't have to manually edit sys\windows\windmain.c if the defines get changed.  If they get changed such that neither is defined, that conditional code layout avoids the assign_soundlib() call altogether.

I'll commit some general changes to sys/windows/Makefile.nmake shortly to make it simpler and friendlier to adjust for additional sound library usage going forward.

For purposes of this discussion, based on the information you provided above, and the assumptions I stated that I was making, this test replacement Makefile.nmake **may** do the build as you've described it:
https://gist.github.com/nhmall/b75477e989d9b1ef449566a2023a9201

You can test it out by dropping a copy of it into your sys\windows directory as "Makefile.nmake", and running through the steps:
```
cd sys\windows
nhsetup.bat
cd ..\..\src
nmake install
```
Please give it a test and we can go from there.

**Comment by nhmall** [comment]
> And as a quick question. Does the game print the message `welcome to NetHack/welcome back to NetHack` before the soundlib is initialized? I think this should be changed, as that message is a great place to start a song file.

The files music_ in sound/wav aren't actually songs or music. They are single-note sound effects at a particular note pitch. They are meant to be used with the sound_hero_playnotes() function implementation, fmod_hero_playnotes(),  in your case. Those are invoked when the hero, a.k.a. **@**, in the game plays an instrument within the game.

I can understand the confusion based on the choice of file names. I think what you are seeking is a way to play (and specify) actual songs or background music or jingles/sounds, which an fmod interface would certainly allow.  

In your sound/fmod/fmod.c, you've placed functionality only into the
    fmod_play_usersound(const char *filename, int32_t volume UNUSED, int32_t idx UNUSED)
function.  

That fmod_play_usersound() function is meant to play a sound file in response to a message appearing in the message window in the game, that has been matched against a regular expression set up in the config file. That's not a particularly efficient way to trigger sound events based on events, or based on achievements, within the game. 

One of the other calls, which hasn't been implemented in yours (or any of the two other sound/... interfaces as of yet, because it was just recently added), triggers when an in-game achievement or an event occurs, not by parsing messages in the message window. 

The core triggers to call that function **have already been added** in the NetHack core code (some of them anyway). Game startup, as you have now suggested, is not one of the triggers  implemented as of yet, but it makes sense. Right now the triggers are based on the achievement already coded into the game (more on those later).

Those in-game achievements are passed as the first parameter to the sound interface function **fmod_achievement(schar ach1, schar ach2, int32_t repeat)**, ach1.
There's another parameter, ach2 that is there just waiting to be used however we want, for other achievements or events within the game. We can add things to it as needed. Suggestions from anyone on what to include are welcome. Each level change is another possibility that comes to mind.

An interface function doesn't have to respond to every achievement that gets passed to it, although it can. As a developer, things can be coded to play sounds or music for whichever ones you want to respond to, and do nothing for the rest. Whatever makes sense.  The core games tells _sound_achievement()_ **when** something happens. It's up to your sound interface implementation to decide how to react with sound or music, and then to do it.

Mapping/associating which sounds to play, and for which achievements or events, might make sense to leave up to the player via their config file. That config file parsing and coding has not been done yet, but it would be done by the config file processing routines, not by an individual sound interface implementation. We'll likely get around to that.

In my opinion, that's the correct way to hook into events and achievements that occur as the game progresses, not by parsing the "welcome message",  or parsing and matching message window messages.

For reference and discussion purposes, here's a list of the achievements coded into the game, and used by  some other reporting/logging features already (from **include/you.h**). They are all passed along to the sound_achievement() function (fmod_achievement(), in your particular case) .  There's a comment with some further suggestions at the end. You've suggested **game startup** as well. We can start to build a list for the unused 2nd parameter to sound_achievement().
```
/*
 * Achievements:  milestones reached during the current game.
 * Numerical order of these matters because they've been encoded in
 * a bitmask in xlogfile.  Reordering would break decoding that.
 * Aside from that, the number isn't significant--they're recorded
 * and eventually disclosed in the order achieved.
 *
 * Since xlogfile could be post-processed by unknown tools, we should
 * limit these to 31 total (it's possible that 32-bit signed longs are
 * the best such tools can offer).  Eventually that is likely to need
 * to change, probably by giving xlogfile an achieve2 field rather
 * than by assuming that 64-bit longs are viable or by squeezing in a
 * 32nd entry by switching to unsigned long.
 */
enum achivements {
    ACH_BELL =  1, /* acquired Bell of Opening */
    ACH_HELL =  2, /* entered Gehennom */
    ACH_CNDL =  3, /* acquired Candelabrum of Invocation */
    ACH_BOOK =  4, /* acquired Book of the Dead */
    ACH_INVK =  5, /* performed invocation to gain access to Sanctum */
    ACH_AMUL =  6, /* acquired The Amulet */
    ACH_ENDG =  7, /* entered end game */
    ACH_ASTR =  8, /* entered Astral Plane */
    ACH_UWIN =  9, /* ascended */
    ACH_MINE_PRIZE = 10, /* acquired Mines' End luckstone */
    ACH_SOKO_PRIZE = 11, /* acquired Sokoban bag or amulet */
    ACH_MEDU = 12, /* killed Medusa */
    ACH_BLND = 13, /* hero was always blond, no, blind */
    ACH_NUDE = 14, /* hero never wore armor */
    /* 1 through 14 were present in 3.6.x; the rest are newer; first,
       some easier ones so less skilled players can have achievements */
    ACH_MINE = 15, /* entered Gnomish Mines */
    ACH_TOWN = 16, /* reached Minetown */
    ACH_SHOP = 17, /* entered a shop */
    ACH_TMPL = 18, /* entered a temple */
    ACH_ORCL = 19, /* consulted the Oracle */
    ACH_NOVL = 20, /* read at least one passage from a Discworld novel */
    ACH_SOKO = 21, /* entered Sokoban */
    ACH_BGRM = 22, /* entered Bigroom (not guaranteed to be in every dgn) */
    /* role's rank titles, beyond first (#0 at level one, not an achievement);
       23..30 are negated if hero is female at the time new rank is gained
       so that disclosing them can use the gender which applied at the time */
    ACH_RNK1 = 23, ACH_RNK2 = 24, ACH_RNK3 = 25, ACH_RNK4 = 26,
    ACH_RNK5 = 27, ACH_RNK6 = 28, ACH_RNK7 = 29, ACH_RNK8 = 30,
    ACH_TUNE = 31, /* discovered the castle drawbridge's open/close tune */
    N_ACH = 32     /* allocate room for 31 plus a slot for 0 terminator */
};
    /*
     * Other potential achievements to track (this comment briefly resided
     * in encodeachieve(topten.c) and has been revised since moving here:
     *  AC <= 0, AC <= -10, AC <= -20 (stop there; lower is better but
     *    not something to encourage with achievements),
     *  got quest summons,
     *  entered quest branch,
     *  chatted with leader,
     *  entered second or lower quest level (implies leader gave the Ok),
     *  entered last quest level,
     *  defeated nemesis (not same as acquiring Bell or artifact),
     *  completed quest (formally, by bringing artifact to leader),
     *  entered rogue level,
     *  entered Fort Ludios level/branch (not guaranteed to be achieveable),
     *  entered Medusa level,
     *  entered castle level,
     *  obtained castle wand (handle similarly to mines and sokoban prizes),
     *  passed Valley level (entered-Gehennom already covers Valley itself),
     *  [assorted demon lairs?],
     *  entered Vlad's tower branch,
     *  defeated Vlad (not same as acquiring Candelabrum),
     *  entered Wizard's tower area within relevant level,
     *  defeated Wizard,
     *  found vibrating square,
     *  entered sanctum level (maybe not; too close to performed-invocation),
     *  [defeated Famine, defeated Pestilence, defeated Death]
     */
```

**Comment by MrEveryDay98** [comment]
@nhmall  Yes, you can specify the install directory for FMOD so its easy to throw into lib\
I'll mess with the nmake stuff later today.

Also, I know that the files in sound\wav aren't related to usersound, I use the YHACS sound pack for my sound effects and a few random songs as `music_` files for testing purposes (which work as intended, they play on a loop in their own channel and aren't interrupted by normal sound effects). 
I asked that question because my old fmod.c implementation was able to play a sound based on the "welcome to NetHack" message, but this current one can't, and I was assuming it was because the selected soundlib isn't actually initiated until after the message is displayed (before this I lazily threw my `init_fmod()` function at the top of the windmain.c main function).

**Comment by MrEveryDay98** [comment]
```
C:\Users\tridu\source\repos\NetHack\src>nmake install

Microsoft (R) Program Maintenance Utility Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Including windsound support
Including fmod support
Autodetected Visual Studio 2022
Windows x86 32-bit target build
tty window support included
curses window support also included
"cflags=-c -nologo -D"_CRT_NONSTDC_NO_DEPRECATE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_LIB" -D"_SCL_SECURE_NO_DEPRECATE" -D"_VC80_UPGRADE=0x0600" -D"_MBCS" -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -D"NDEBUG" -D"YY_NO_UNISTD_H" -DHAS_STDINT_H -DHAS_INLINE -EHsc -fp:precise -Gd -GF -GS -Gy -sdl -WX- -Zc:forScope -Zc:wchar_t -Zi -analyze- -D"_DEBUG" -MTd -RTC1 -Od /fsanitize=address -D_X86_=1 -DWIN32 -D_WIN32 -W4 -wd4100 -wd4244 -wd4245 -wd4310 -wd4706 -w44777 -wd4820 -w44774 /I..\include /I..\sys\windows /I..\submodules\lua -I../lib/api/core/inc -DDLB -DSAFEPROCS -DSND_LIB_WINDSOUND -DSND_LIB_FMOD -DUSER_SOUNDS "
tile2bmp.c
C:\Users\tridu\source\repos\NetHack\sys\windows\win32api.h(46): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.
```

**Comment by nhmall** [comment]
> ```
> C:\Users\tridu\source\repos\NetHack\src>nmake install
> 
> Microsoft (R) Program Maintenance Utility Version 14.30.30709.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> Including windsound support
> Including fmod support
> Autodetected Visual Studio 2022
> Windows x86 32-bit target build
> tty window support included
> curses window support also included
> "cflags=-c -nologo -D"_CRT_NONSTDC_NO_DEPRECATE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_LIB" -D"_SCL_SECURE_NO_DEPRECATE" -D"_VC80_UPGRADE=0x0600" -D"_MBCS" -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -D"NDEBUG" -D"YY_NO_UNISTD_H" -DHAS_STDINT_H -DHAS_INLINE -EHsc -fp:precise -Gd -GF -GS -Gy -sdl -WX- -Zc:forScope -Zc:wchar_t -Zi -analyze- -D"_DEBUG" -MTd -RTC1 -Od /fsanitize=address -D_X86_=1 -DWIN32 -D_WIN32 -W4 -wd4100 -wd4244 -wd4245 -wd4310 -wd4706 -w44777 -wd4820 -w44774 /I..\include /I..\sys\windows /I..\submodules\lua -I../lib/api/core/inc -DDLB -DSAFEPROCS -DSND_LIB_WINDSOUND -DSND_LIB_FMOD -DUSER_SOUNDS "
> tile2bmp.c
> C:\Users\tridu\source\repos\NetHack\sys\windows\win32api.h(46): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
> NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
> Stop.
> ```

When you install Visual Studio 2022, in your list of All Apps from the Start button, it includes ways to start command prompts for doing various types of compiles. 

Start the command prompt from **x64 Native Tools Command Prompt for VS 2022** for command line development of 64-bit applications (x64), or from **x64_x86 Cross Tools Command Prompt for VS 2022** for command line development of 32-bit applications (x86). Either can build NetHack, but the NetHack save files are not compatible between them.
vscommand-prompts. 

Starting the command prompt from one of those should ensure that everything is set up properly for carrying out builds.  That's probably the most straightforward way to proceed.

I'll also work on similar changes for Makefile.mingw32 that I had done for Makefile.nmake, those meant to make it easy to choose sound libraries to include in the build at will.

**Comment by MrEveryDay98** [comment]
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.0.5
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
C:\Users\tridu\source\repos\NetHack\src>nmake install

Microsoft (R) Program Maintenance Utility Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Host architecture is x64
Target architecture is x64
Including windsound support
Including fmod support
Autodetected Visual Studio 2022
Windows x64 64-bit target build
tty window support included
curses window support also included
"cflags=-c -nologo -D"_CRT_NONSTDC_NO_DEPRECATE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_LIB" -D"_SCL_SECURE_NO_DEPRECATE" -D"_VC80_UPGRADE=0x0600" -D"_MBCS" -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -D"NDEBUG" -D"YY_NO_UNISTD_H" -DHAS_STDINT_H -DHAS_INLINE -EHsc -fp:precise -Gd -GF -GS -Gy -sdl -WX- -Zc:forScope -Zc:wchar_t -Zi -analyze- -D"_DEBUG" -MTd -RTC1 -Od /fsanitize=address -D_AMD64_=1 -DWIN64 -D_WIN64 -DWIN32 -D_WIN32 -W4 -wd4100 -wd4244 -wd4245 -wd4310 -wd4706 -w44777 -wd4820 -w44774 /I..\include /I..\sys\windows /I..\submodules\lua -I../lib/api/core/inc -DDLB -DSAFEPROCS -DSND_LIB_WINDSOUND -DSND_LIB_FMOD -DUSER_SOUNDS "
tile2bmp.c
C:\Users\tridu\source\repos\NetHack\win\share\tile2bmp.c : fatal error C1083: Cannot open compiler generated file: 'C:\Users\tridu\source\repos\NetHack\src\objutil\x64\tile2bmp.o': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.EXE"' : return code '0x1'
Stop.

**Comment by nhmall** [comment]
> tile2bmp.c
> C:\Users\tridu\source\repos\NetHack\win\share\tile2bmp.c : fatal error C1083: Cannot open compiler generated file: 'C:\Users\tridu\source\repos\NetHack\src\objutil\x64\tile2bmp.o': No such file or directory
> NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.EXE"' : return code '0x1'
> Stop.

That's strange. It is stating that it can't create the output file 'C:\Users\tridu\source\repos\NetHack\src\objutil\x64\tile2bmp.o'.

Try cleaning things up with "nmake spotless" and try it again as follows:
```
nmake spotless
nmake install
```

**Comment by MrEveryDay98** [comment]
That fixed it, last issue seems to be it can't find fmod.h despite the path being correct
`SOUNDLIBINCL = $(SOUNDLIBINCL) -I../lib/api/core/inc`
\~\~\~\~\~
`
..\sound\fmod\fmod.c(7): fatal error C1083: Cannot open include file: 'fmod.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.
`

**Comment by nhmall** [comment]
> That fixed it, last issue seems to be it can't find fmod.h despite the path being correct `SOUNDLIBINCL = $(SOUNDLIBINCL) -I../lib/api/core/inc` ~~~~~ `..\sound\fmod\fmod.c(7): fatal error C1083: Cannot open include file: 'fmod.h': No such file or directory NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.EXE"' : return code '0x2' Stop.`

Okay, making some progress, so that is good.
Let's get more information from your build. 
Please edit the Makefile that you are using and look for these lines:
```
#       #################################################
#       #                                               #
#       # Nothing below here should have to be changed. #
#       #                                               #
#       #################################################
#
#==============================================================================
#
# if next line is commented out, full compiler command lines will be output
Q=@

```
Please change that last line from "Q=@" to "#Q=@". Comment it out, in other words.
Then please take it almost from the top, by using "nmake clean". After that edit to the Makefile, all the compiler command line details will be included in the output and we'll want to see the compile command for ..\sound\fmod\fmod.c in particular.
```
nmake clean
nmake install
```
Also, could you please provide a dir listing of the files in **..\lib\api\core\inc**
```
dir ..\lib\api\core\inc
```

**Comment by MrEveryDay98** [comment]
My bad, when I moved fmod to the nethack dir I put it in lib\api\core\core\inc.
Either way, a new error came up
`
Linking ../binary/NetHack.exe
        link.exe /NOLOGO /INCREMENTAL:NO /DEBUG kernel32.lib   advapi32.lib gdi32.lib  ole32.lib Shell32.lib /MACHINE:X64 /NOLOGO /INCREMENTAL:NO /DEBUG -subsystem:console,5.02 /STACK:2048 /PDB:..\binary\NetHack.PDB /MAP:objtty\x64\NetHack.MAP  user32.lib winmm.lib   ..\lib\pdcursesmod-x64.lib ..\lib\lua5.4.4-x64-static.lib  ..\lib\api\core\lib\x64\fmod_vc.lib  kernel32.lib   advapi32.lib gdi32.lib  ole32.lib Shell32.lib bcrypt.lib -out:..\binary\NetHack.exe @NetHack.lnk
LINK : fatal error LNK1181: cannot open input file '..\lib\api\core\lib\x64\fmod_vc.lib'
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\link.exe"' : return code '0x49d'
Stop.
`

**Comment by nhmall** [comment]
> cannot open input file '..\lib\api\core\lib\x64\fmod_vc.lib'

So, that one is saying it cannot open input file '..\lib\api\core\lib\x64\fmod_vc.lib'.
That's the fmod library file that the build is trying to link with.
Can you please provide a dir listing of **..\lib\api\core\lib\x64** next?
```
dir ..\lib\api\core\lib\x64
```

**Comment by MrEveryDay98** [comment]
```
C:\Users\tridu\source\repos\NetHack\src>dir ..\lib\api\core\x64\
 Volume in drive C is SSD Main
 Volume Serial Number is 1C44-8E44

 Directory of C:\Users\tridu\source\repos\NetHack\lib\api\core\x64

01/22/2023  19:21    <DIR>          .
01/22/2023  19:21    <DIR>          ..
12/01/2022  01:02         1,849,856 fmod.dll
12/01/2022  01:02         2,085,376 fmodL.dll
12/01/2022  01:02           349,802 fmodL_vc.lib
12/01/2022  01:02           347,924 fmod_vc.lib
               4 File(s)      4,632,958 bytes
               2 Dir(s)  16,178,610,176 bytes free

C:\Users\tridu\source\repos\NetHack\src>
```

**Comment by MrEveryDay98** [comment]
Ah, another layer 8 error. My own paths are messed up

**Comment by MrEveryDay98** [comment]
She builds!

image

**Comment by nhmall** [comment]
> She builds!

Great!  Does the sound work?
It sounds like no further Makefile.nmake changes were needed then, beyond those in 
https://gist.github.com/nhmall/b75477e989d9b1ef449566a2023a9201, is that correct?

**Comment by MrEveryDay98** [comment]
Sounds work great

**Comment by nhmall** [comment]
Your sound\fmod\fmod.c file needs a Copyright notice at the top, on the second line.
/* Copyright (c) YOUR_NAME, 2023. */

I've converted the pull request back to draft.

**Comment by MrEveryDay98** [comment]
Done

**Comment by nhmall** [comment]
I'm working on the splash screen issue.
Some modifications to make that work appropriately are forthcoming. Not to your pull request, I mean to NetHack in general.

**Comment by nhmall** [comment]
There's another thing I'd like to fix in the Makefile: I'd like to change the assumed paths in the Makefile.nmake from
**..\lib\api\core\inc** to **..\lib\fmod\api\core\inc**, and **..\lib\api\core\lib\x64\fmod_vc.lib** to **..\lib\fmod\api\core\lib\x64\fmod_vc.lib**.  

The name "api" isn't very informative and other stuff goes into that lib dir too, so a mystery name at the top level could cause head-scratching.

Will that change cause you any issues that you can't work around?

**Comment by MrEveryDay98** [comment]
That shouldn't cause any issues

**Comment by nhmall** [comment]
There has been some evolution to the sound interface. See sample at:
https://gist.github.com/nhmall/93b1036daa9ba4cafe3fd30b57328a41

There is also a description in doc/sound.txt in the NetHack-3.7 source tree.

**Comment by MrEveryDay98** [comment]
I don't really have any time to work on this PR, I'd greatly appreciate if someone were to take over this

**Comment by MrEveryDay98** [comment]
@nhmall mind having a look at this, stumped as to why I'm getting 2 `too many initializers` errors

**Comment by nhmall** [comment]
The sound/fmod/fmod.c is glue code for building if you have fmod. We can merge that into the work-in-progress sources and you or someone can go from there and close this particular pull request. sound/fmod/fmod.c will need a copyright comment, as I don't think the latest pull request changes included one.

Does it work with this patch?
```
--- ../other/sound/fmod/fmod.c	2023-09-16 09:12:45.168773900 -0400
+++ sound/fmod/fmod.c	2023-09-16 08:07:09.553144600 -0400
@@ -6,29 +7,31 @@
 #include "hack.h"
 #include "fmod.h"
 
-FMOD_SYSTEM *systemvar;
-FMOD_SOUND *soundvar;
-FMOD_CHANNEL *channel1;
-FMOD_CHANNEL *channelMus;
-
-#define soundlib_fmod soundlib_nosound + 1
+static FMOD_SYSTEM *systemvar;
+static FMOD_SOUND *soundvar;
+static FMOD_CHANNEL *channel1;
+static FMOD_CHANNEL *channelMus;
 
 static void fmod_init_nhsound(void);
 static void fmod_exit_nhsound(const char *);
 static void fmod_achievement(schar, schar, int32_t);
 static void fmod_soundeffect(char *, int32_t, int32_t);
-static void fmod_hero_playnotes(int32_t, char *, int32_t);
-static void fmod_play_usersound(char *, int32_t, int32_t);
+static void fmod_hero_playnotes(int32_t, const char *, int32_t);
+static void fmod_play_usersound(const char *, int32_t, int32_t);
+static void fmod_ambience(int32_t, int32_t, int32_t);
+static void fmod_verbal(char *, int32_t, int32_t, int32_t, int32_t);
 
 struct sound_procs fmod_procs = {
     SOUNDID(fmod),
-    SNDCAP_USERSOUNDS,
+    SOUND_TRIGGER_USERSOUNDS | 0,
     fmod_init_nhsound,
     fmod_exit_nhsound,
     fmod_achievement,
     fmod_soundeffect,
     fmod_hero_playnotes,
     fmod_play_usersound,
+    fmod_ambience,
+    fmod_verbal
 };
 
 static void
@@ -51,39 +54,46 @@
 static void
 fmod_achievement(schar ach1, schar ach2, int32_t repeat)
 {
-
-
+    //  to be added in future
 }
 
 /* fulfill SNDCAP_SOUNDEFFECTS */
 static void
-fmod_soundeffect(char *desc, int32_t seid, int volume)
+fmod_soundeffect(char *desc, int32_t seid, int32_t volume)
 {
-
+    //  to be added in future
 }
 
 /* fulfill SNDCAP_HEROMUSIC */
 static void fmod_hero_playnotes(int32_t instrument, char *str, int32_t volume)
 {
-
+    //  to be added in future
 }
 
-/* fulfill  SNDCAP_USERSOUNDS */
+/* fulfill  SOUND_TRIGGER_USERSOUNDS */
 static void
-fmod_play_usersound(char *filename, int32_t volume UNUSED, int32_t idx UNUSED)
+fmod_play_usersound(const char *filename, int32_t volume UNUSED, int32_t idx UNUSED)
 {
     FMOD_System_CreateSound(systemvar, filename, FMOD_CREATESAMPLE, 0,
                             &soundvar);
-    if (strstr(filename, "music_") != 0) {
+    if (strstr(filename, "music_") != NULL) {
         FMOD_Channel_Stop(channelMus);
         FMOD_System_PlaySound(systemvar, soundvar, 0, 0, &channelMus);
         FMOD_Channel_SetMode(channelMus, FMOD_LOOP_NORMAL);
-        FMOD_Channel_SetVolume(channelMus, .5);
     } else {
         FMOD_Channel_Stop(channel1);
         FMOD_System_PlaySound(systemvar, soundvar, 0, 0, &channel1);
     }
 }
 
+static void
+fmod_ambience(int32_t ambienceid, int32_t ambience_action,
+                int32_t hero_proximity)
+{
+    //  to be added in future
+}
+
+
+
 #endif /* SND_LIB_FMOD  */
        /* end of fmod.c */

```

**Comment by nhmall** [comment]
Once you have it working to your satisfaction, press [Ready For Review] to take the pull request out of draft and indicate that it is ready for merging.

**Comment by MrEveryDay98** [comment]
The only issue with this patch is the `too many initializers` errors I am getting which is preventing it from building, I have no idea what is causing this. Once I can figure that out I will take it out of draft

**Comment by nhmall** [comment]
Are you still getting that even with the patch above applied? Can you provide the full error message that you are seeing?

**Comment by MrEveryDay98** [comment]
Yes I am still getting that error
```
6>------ Build started: Project: NetHackW, Configuration: Debug|Win32 ------
6>  fmod.c
6>C:\Users\tridu\source\repos\NetHack\lib\fmod\api\core\inc\fmod_dsp.h(188,6): warning C4201: nonstandard extension used: nameless struct/union
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(35,1): error C2078: too many initializers
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(33,5): error C2078: too many initializers
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(49,23): warning C4047: 'function': 'FMOD_SYSTEM *' differs in levels of indirection from 'FMOD_SYSTEM **'
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(49,23): warning C4024: 'FMOD_System_Close': different types for formal and actual parameter 1
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(50,25): warning C4047: 'function': 'FMOD_SYSTEM *' differs in levels of indirection from 'FMOD_SYSTEM **'
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(50,25): warning C4024: 'FMOD_System_Release': different types for formal and actual parameter 1
6>C:\Users\tridu\Source\Repos\NetHack\sound\fmod\fmod.c(68,59): warning C4028: formal parameter 2 different from declaration
```

**Comment by nhmall** [comment]
Does the sound_procs definition in the include/sndprocs.h you are using look like this (with 8 function pointers after sound_triggers)?
```
struct sound_procs {
    const char *soundname;
    enum soundlib_ids soundlib_id;
    unsigned long sound_triggers; /* capabilities in the port */
    void (*sound_init_nhsound)(void);
    void (*sound_exit_nhsound)(const char *);
    void (*sound_achievement)(schar, schar, int32_t);
    void (*sound_soundeffect)(char *desc, int32_t, int32_t volume);
    void (*sound_hero_playnotes)(int32_t instrument, const char *str,
                                 int32_t volume);
    void (*sound_play_usersound)(char *filename, int32_t volume, int32_t idx);
    void (*sound_ambience)(int32_t ambience_action, int32_t ambienceid,
                           int32_t proximity);
    void (*sound_verbal)(char *text, int32_t gender, int32_t tone,
                         int32_t vol, int32_t moreinfo);
};
```
Could you have an outdated stale copy of sndprocs.h in your include paths somewhere?

**Comment by MrEveryDay98** [comment]
That was the issue lol, my local repo did not have the latest changes, now I just gotta fix this on my end
`Error	MSB8036	The Windows SDK version 10.0.20348.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	C:\Users\tridu\Source\Repos\NetHack\sys\windows\vs\uudecode\uudecode.vcxproj	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets`

**Comment by nhmall** [comment]
As for the other errors/warnings, I don't know fmod myself, but a search turned up this: 
https://www.fmod.com/docs/2.00/api/core-api-system.html#system_create
which seems to indicate that  FMOD_System_Create() function only takes a single parameter, but you are calling it with two in fmod_init_nhsound().

**Pull request closed without merging**
