### PR TITLE
Remove NODUMPENUMS config option

### PR DESCRIPTION
**Pull request by softdevca**
Remove NODUMPENUMS config option as the memory savings is trivial, especially as ENHANCED_SYMBOLS is set by default,

### CODE REVIEW

**Comment by nhmall** [comment]
Why does this pull request include a change to d8c49ec9d1?

**Comment by softdevca** [comment]
Sorry, not sure I understand.  There is one commit that changed five files.

**Comment by nhmall** [comment]
Your pull request includes the following change to src/allmain.c that alters something that someone else added in d8c49ec9d1ec55e5150480009ee9dce5011ab6b0
```
- /*-Copyright (c) Robert Patrick Rankin, 2012. */
+ /* Copyright (c) Robert Patrick Rankin, 2012. */
```

**Comment by copperwater** [comment]
I think that - instead of a space before Copyright is a typo?

**Comment by softdevca** [comment]
Yes, it was just a type-o in the existing code.  I've updated the PR to be based off the current state of the repository.

**Pull request closed without merging**
