### PR TITLE
Net hack 3.7 mingw32

### PR DESCRIPTION
**Pull request by feiyunw**
For my MSYS2/mingw32 to build properly:
```
wangfy@DESKTOP-8KQFTRT MINGW64 /d/prj/NetHack/src
$ mingw32-make -f Makefile.gcc all
----
NOTE: This build will include tile support.
----
gcc -c -mms-bitfields -I../include -I../sys/windows -I../lib/lua-5.4.3/src    -DTILES -DMSWIN_GRAPHICS -DWIN32CON -D_WIN32_IE=0x0400 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 -DDLB -DSAFEPROCS -DGUISTUB  -oo/guistub.o ../sys/windows/stubs.c
gcc -c -mms-bitfields -I../include -I../sys/windows -I../lib/lua-5.4.3/src    -DTILES -DMSWIN_GRAPHICS -DWIN32CON -D_WIN32_IE=0x0400 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 -DDLB -DSAFEPROCS -oo/windsys.o  ../sys/windows/windsys.c
In file included from D:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from ../sys/windows/win32api.h:40,
                 from ../sys/windows/win10.h:8,
                 from ../sys/windows/windsys.c:14:
../sys/windows/win10.h:14:16: error: redefinition of 'struct DPI_AWARENESS_CONTEXT__'
   14 | DECLARE_HANDLE(DPI_AWARENESS_CONTEXT);
      |                ^~~~~~~~~~~~~~~~~~~~~
D:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:155:1: note: originally defined here
```
and
```
Linking ../binary/NetHack.exe...
gcc   -o../binary/NetHack.exe o/windmain.o o/windsys.o o/win10.o o/safeproc.o o/nhlan.o o/ntsound.o o/dlb.o  o/allmain.o  o/alloc.o    o/apply.o    o/artifact.o o/attrib.o   o/ball.o     o/bones.o    o/botl.o o/cmd.o      o/dbridge.o  o/decl.o     o/detect.o o/dig.o      o/display.o  o/do.o       o/do_name.o o/do_wear.o  o/dog.o      o/dogmove.o  o/dokick.o o/dothrow.o  o/drawing.o  o/dungeon.o  o/eat.o o/end.o      o/engrave.o  o/exper.o    o/explode.o o/extralev.o o/files.o    o/fountain.o o/hack.o o/hacklib.o  o/insight.o  o/invent.o   o/isaac64.o o/light.o    o/lock.o     o/mail.o     o/makemon.o o/mdlib.o    o/mcastu.o   o/mhitm.o    o/mhitu.o o/minion.o   o/mklev.o    o/mkmap.o    o/mkmaze.o o/mkobj.o    o/mkroom.o   o/mon.o      o/mondata.o o/monmove.o  o/monst.o    o/mplayer.o  o/mthrowu.o o/muse.o     o/music.o    o/o_init.o   o/objects.o  o/objnam.o   o/options.o  o/pager.o    o/pickup.o o/pline.o    o/polyself.o o/potion.o   o/pray.o o/priest.o   o/quest.o    o/questpgr.o o/random.o o/read.o     o/rect.o     o/region.o   o/restore.o o/rip.o      o/rnd.o      o/role.o     o/rumors.o o/save.o     o/sfstruct.o o/shk.o      o/shknam.o o/sit.o      o/sounds.o   o/sp_lev.o   o/spell.o o/steal.o    o/steed.o    o/symbols.o  o/sys.o o/teleport.o o/timeout.o  o/topten.o   o/track.o o/trap.o     o/u_init.o   o/uhitm.o    o/vault.o o/vision.o   o/weapon.o   o/were.o     o/wield.o o/windows.o  o/wizard.o   o/worm.o     o/worn.o o/write.o    o/zap.o o/cppregex.o   o/version.o o/nhlua.o    o/nhlsel.o    o/nhlobj.o o/topl.o     o/getline.o  o/wintty.o o/consoletty.o o/tile.o \
        o/guistub.o o/date.o o/conres.o  o/lua-5.4.3.static.a \
        -lgdi32 -lwinmm -lshell32 -lole32 -luuid -lbcrypt -static -lstdc++
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: o/windsys.o:windsys.c:(.bss+0x160): multiple definition of `getreturn_enabled'; o/windmain.o:windmain.c:(.bss+0x100): first defined here
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: o/guistub.o:stubs.c:(.bss+0x0): multiple definition of `GUILaunched'; o/consoletty.o:consoletty.c:(.bss+0x34): first defined here
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile.gcc:895: ../binary/NetHack.exe] Error 1
```

### CODE REVIEW

**Comment by nhmall** [comment]
Where are you obtaining your mingw from and what version?  Your PR fails for me with unknown type name 'DPI_AWARENESS_CONTEXT', but it is likely version mismatches with what I tried and what you are using.

**Comment by feiyunw** [comment]
Try "pacman -Syuu" to update your MSYS2 system please.
The new two patches can bring up mingw32 64bit built NetHackW.exe in my Windows 10, so we needn't SKIP_NETHACKW any more.

**Comment by feiyunw** [comment]
Should set --target option for windres to build 64bit NetHackW.exe:
```
ifeq "$(MSYSTEM)" "MINGW64"
rc = windres --target=pe-x86-64
endif
```

**Comment by nhmall** [comment]
@feiyunw I had some build success with this PR after following the suggestions.  Thanks.

**Comment by feiyunw** [comment]
Makefile.mingw32 and Makefile.mingw32.depend are intended to replace Makefile.gcc.
To use them:
```
cd /d/prj/NetHack/src
cp ../sys/windows/Makefile.mingw32* .
mingw32-make -f Makefile.mingw32 clean
mingw32-make -f Makefile.mingw32 depend
mingw32-make -f Makefile.mingw32
```
Improvements:
- Add $(USE_LUADLL) to release lua-5.4.3.dll, instead of link static lua.lib into .exe files.
- Add windres "--target" option, to fix the NetHackW.exe startup problem.
- Add "-s" option to $(LDFLAGS) in release mode, to make exe/dll smaller.
- Add $(CLEAN_DIR) and $(CLEAN_FILE) to track what to clean.
- Remove *.tag, but use "order-only prerequisites" to make directory before any '.o' is built.
- Use make variables and functions to improve readability.
- Each project has its own directory to hold object files, to fix the interference problem between different projects, like NetHack.exe object files were built with "-DTILES".
- Add "-mconsole" option when linking NetHack.exe, to fix that sometimes GetStdHandle returned with invalid handle error.
- Add ".PHONY" statements.
- Use "gcc -E -MM -MT" to implement semi-auto "Prerequisites Generating".

FYI:
- [Make: order-only prerequisite](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html#Prerequisite-Types)
- [Make: Phony Targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html#Phony-Targets)
- [Make: Quick Reference](https://www.gnu.org/software/make/manual/html_node/Quick-Reference.html#Quick-Reference)
- [Make: Generating Prerequisites Automatically](https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html#Automatic-Prerequisites)
- [GCC: -mconsole ](https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/x86-Windows-Options.html#x86-Windows-Options)
- [GetStdHandle](https://docs.microsoft.com/en-us/windows/console/getstdhandle)
"Specifying /SUBSYSTEM:CONSOLE requests that the operating system fill the handles with a console session on startup".
- [GCC: -MT target](https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Preprocessor-Options.html#index-MT)

**Comment by nhmall** [comment]
That worked well! Nice.
I'll merge this PR in the next day or two.

**Comment by nhmall** [comment]
Commits 96de8d58d65198729ab7142c9dc208209fa7401b and some prior to it have all of this included. Thanks.
Please feel free to evolve the mingw build further if you want through new pull requests.

**Pull request closed without merging**
